

export const INIT_COMBOS = [
    {
      id: 1,
      name: "Combo Đôi Lãng Mạn",
      description: "2 Bắp Lớn + 2 Pepsi 500ml – Dành cho các cặp đôi yêu điện ảnh",
      price: 120000,
      originalPrice: 150000,
      image: "https://cdn.shopify.com/s/files/1/0070/7032/files/popcorn-combo.jpg",
      items: ["2 Bắp Lớn", "2 Pepsi 500ml"],
      category: "Combo Đôi",
      maxPerOrder: 3,
      isActive: true,
      isSeasonal: false,
      soldCount: 2840,
      tag: "Bán chạy",
      sortOrder: 1,
    },
    {
      id: 2,
      name: "Combo Gia Đình Vui",
      description: "4 Bắp Nhỏ + 4 Sprite 330ml + 1 Hotdog – Trọn vẹn niềm vui",
      price: 220000,
      originalPrice: 280000,
      image: "",
      items: ["4 Bắp Nhỏ", "4 Sprite 330ml", "1 Hotdog"],
      category: "Combo Gia Đình",
      maxPerOrder: 2,
      isActive: true,
      isSeasonal: false,
      soldCount: 1560,
      tag: "Mới",
      sortOrder: 2,
    },
    {
      id: 3,
      name: "Combo Solo Tiết Kiệm",
      description: "1 Bắp Vừa + 1 Nước Suối – Nhẹ nhàng, tiết kiệm cho 1 người",
      price: 55000,
      originalPrice: 70000,
      image: "",
      items: ["1 Bắp Vừa", "1 Nước Suối 500ml"],
      category: "Combo Solo",
      maxPerOrder: 5,
      isActive: true,
      isSeasonal: false,
      soldCount: 3990,
      tag: "Phổ biến",
      sortOrder: 3,
    },
    {
      id: 4,
      name: "Combo Mùa Hè Trái Cây",
      description: "2 Bắp Nhỏ + 2 Nước Ép Cam Tươi – Mát lạnh ngày hè",
      price: 105000,
      originalPrice: 130000,
      image: "",
      items: ["2 Bắp Nhỏ", "2 Nước Ép Cam 350ml"],
      category: "Combo Đôi",
      maxPerOrder: 3,
      isActive: false,
      isSeasonal: true,
      soldCount: 430,
      tag: "Theo mùa",
      sortOrder: 4,
    },
    {
      id: 5,
      name: "Combo VIP Premium",
      description: "1 Bắp Jumbo Bơ Mặn + 1 Nước Ngọt Lớn + 1 Kẹo Gummy – Đẳng cấp thượng lưu",
      price: 145000,
      originalPrice: 180000,
      image: "",
      items: ["1 Bắp Jumbo Bơ Mặn", "1 Coca-Cola Lớn 600ml", "1 Kẹo Gummy"],
      category: "Combo VIP",
      maxPerOrder: 2,
      isActive: true,
      isSeasonal: false,
      soldCount: 870,
      tag: "VIP",
      sortOrder: 5,
    },
  ];
  
  export const CATEGORIES = ["Tất cả", "Combo Solo", "Combo Đôi", "Combo Gia Đình", "Combo VIP"];
  
  export const TAG_CONFIG = {
    "Bán chạy": { color: "#dc2626", bg: "#fef2f2", border: "#fca5a5", icon: "FaFire" },
    "Mới":      { color: "#7c3aed", bg: "#f5f3ff", border: "#c4b5fd", icon: "MdLocalOffer" },
    "Phổ biến": { color: "#059669", bg: "#ecfdf5", border: "#6ee7b7", icon: "MdTrendingUp" },
    "Theo mùa": { color: "#0284c7", bg: "#f0f9ff", border: "#7dd3fc", icon: "MdStar" },
    "VIP":      { color: "#b45309", bg: "#fffbeb", border: "#fcd34d", icon: "MdEmojiEvents" },
  };
  
  export const EMPTY_FORM = {
    name: "",
    description: "",
    price: "",
    originalPrice: "",
    image: "",
    items: [""],
    category: "Combo Đôi",
    maxPerOrder: 3,
    isActive: true,
    isSeasonal: false,
    tag: "Mới",
  };
  
  export const DARK = {
    bg: "#0a0a18",
    bgCard: "#16213e",
    bgDark: "#0f0f1a",
    bgDeep: "#05050a",
    ink: "#f7fafc",
    ink2: "#e2e8f0",
    ink3: "#a0aec0",
    ink4: "#718096",
    ink5: "#4a5568",
    ink6: "#2d3748",
  };